version: "2.1"

services:
  globalenv:
    image: debian
    extends:
      file: volumes.yml
      service: globalenv
    network_mode: "bridge"

  proxy:
    build: ./etc/proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    ports:
        - "80:80"
    network_mode: "bridge"

  mysql:
    extends:
      file: ./etc/mysql/docker-compose.yml
      service: mysql
    volumes_from:
      - globalenv
    network_mode: "bridge"

  postgresql:
    extends:
      file: ./etc/postgresql/docker-compose.yml
      service: postgresql
    volumes_from:
      - globalenv
    network_mode: "bridge"

  web-pentaho:
    build: ./etc/web-pentaho
    environment:
      - VIRTUAL_HOST=web-pentaho.prod
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
      - postgresql:postgrehost
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "8081"

  web-tomcat7:
    build: ./etc/web-tomcat7
    environment:
      - VIRTUAL_HOST=web-tomcat7.prod
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
      - postgresql:postgrehost
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "8080"

  web-transparencia:
    build: ./etc/web-php56
    environment:
      - VIRTUAL_HOST=transparencia.prod
    volumes:
      - ./etc/web-php56/conf/nginx/transparencia.conf:/etc/nginx/conf.d/transparencia.conf
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
      - postgresql:postgrehost
      - web-tomcat7:web-tomcat7.prod
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "80"
    entrypoint: /usr/bin/supervisord

  web-redesimples:
    build: ./etc/web-php56
    environment:
      - VIRTUAL_HOST=redesimples.prod
    volumes:
      - ./etc/web-php56/conf/nginx/redesimples.conf:/etc/nginx/conf.d/redesimples.conf
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "80"
    entrypoint: /usr/bin/supervisord

  web-urbem:
    build: ./etc/web-php71
    environment:
      - VIRTUAL_HOST=urbem.prod
    volumes:
      - ./etc/web-php71/conf/nginx/urbem.conf:/etc/nginx/conf.d/urbem.conf
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
      - postgresql:postgrehost
      - web-tomcat7:web-tomcat7.prod
      - web-rabbitmq:web-rabbitmq.prod
      - web-transparencia:transparencia.prod
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "80"
    entrypoint: /usr/bin/supervisord

  web-rabbitmq:
    build: ./etc/web-rabbitmq
    environment:
      - VIRTUAL_HOST=web-rabbitmq.prod
    network_mode: "bridge"
    links:
      - mysql:mysqlhost
      - postgresql:postgrehost
      - proxy:proxy-server
      - web-pentaho:web-pentaho.prod
    privileged: true
    volumes_from:
      - globalenv
    ports:
      - "4369"
      - "5671"
      - "5672"
      - "15672"