version: '2.1'

services:
  mysql:
      build: .
      ports:
        - "3636:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: project_rede_simples
      volumes:
        - ../../var/lib/mysql:/var/lib/mysql
        - ./my.cnf:/etc/mysql/conf.d/my.cnf